[package]
name = "rs_ipc"
version = "0.1.0"
edition = "2024"

[profile.release]
lto = "fat"
codegen-units = 1

[lib]
name = "rs_ipc"
crate-type = ["cdylib", "rlib"]

[dependencies]
rustix = { version = "1.1.4", default-features = false, features = ["std", "mm", "shm", "thread", "linux_latest"] }
rayon = { version = "1.12.0", optional = true }
pyo3 = { version = "0.28.3", optional = true, features = ["auto-initialize"] }

[features]
default = ["python"]
python = ["dep:pyo3", "dep:rayon"]

[dev-dependencies]
criterion = "0.8.2"

[[bench]]
name = "ipc_bench"
harness = false

