[package]
name = "rs_ipc"
version = "0.1.0"
edition = "2021"

[profile.release]
lto = "fat"

[lib]
name = "rs_ipc"
crate-type = ["cdylib", "rlib"]

[dependencies]
rustix = { version = "1.1.2", default-features = false, features = ["std", "mm", "shm", "thread", "linux_latest"] }
rayon = "1.11.0"
pyo3 = { version = "0.27.1", optional = true }

[dev-dependencies]
pyo3 = { version = "0.27.1", features = ["auto-initialize"] }

[features]
default = ["python"]
python = ["dep:pyo3"]
nightly-features = ["python"]
