[package]
name = "rs_ipc"
version = "0.1.0"
edition = "2024"

[profile.release]
lto = "fat"

[lib]
name = "rs_ipc"
crate-type = ["cdylib", "rlib"]

[dependencies]
rustix = { version = "1.1.3", default-features = false, features = ["std", "mm", "shm", "thread", "linux_latest"] }
rayon = { version = "1.11.0", optional = true }
pyo3 = { version = "0.27.2", optional = true, features = ["auto-initialize"] }

[features]
default = ["python"]
python = ["dep:pyo3", "dep:rayon"]
nightly-features = ["python"]
